In [7]:
import numpy as np

In [11]:
ar = np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
ar + ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
ar - ar


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
ar * ar

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [19]:
ar / ar

C:\Users\chien\AppData\Local\Temp\ipykernel_9916\1071685828.py:1: RuntimeWarning: invalid value encountered in divide
  ar / ar


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [21]:

np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [23]:
np.sin(ar)


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])